# Generated by Django 5.1.7 on 2025-03-11 06:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(editable=False, help_text='A unique three-digit ID for the department.', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'ID must be a three-digit number')])),
                ('name', models.CharField(help_text='Name of the department.', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s&]+$', 'Name must contain only letters, spaces, or &')])),
                ('faculty', models.CharField(choices=[('I&C', 'IC'), ('E&T', 'ET'), ('I&R', 'IR'), ('LS', 'LS'), ('LAMS', 'LAMS'), ('MS', 'MS'), ('SC', 'SC'), ('CCSD', 'CCSD')], help_text='Faculty the department belongs to.', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Marks the department as deleted (soft delete).')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['faculty'], name='academics_d_faculty_3673e6_idx'), models.Index(fields=['created_at'], name='academics_d_created_227bed_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'faculty'), name='unique_name_faculty')],
            },
        ),
    ]
